In [1]:
!pip install opencv-python

In [1]:
import numpy as np
import cv2 ,time


In [2]:
#Capturing first frame

In [3]:
video =cv2.VideoCapture(0)
check,frame=video.read()
print(check)
print(frame)
time.sleep(3)
cv2.imshow("Capture",frame)
cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()

True
[[[25 49 47]
  [28 51 49]
  [29 55 52]
  ...
  [34 84 73]
  [39 84 77]
  [39 84 77]]

 [[37 52 46]
  [34 49 43]
  [32 53 51]
  ...
  [34 84 73]
  [37 82 73]
  [36 81 72]]

 [[29 38 37]
  [39 49 48]
  [35 52 50]
  ...
  [37 86 72]
  [41 85 74]
  [39 82 71]]

 ...

 [[36 62 59]
  [35 61 58]
  [34 62 59]
  ...
  [ 4 28 26]
  [ 0 26 23]
  [ 0 23 21]]

 [[27 61 58]
  [28 63 59]
  [31 64 61]
  ...
  [ 2 28 26]
  [ 3 25 20]
  [ 1 22 18]]

 [[27 60 57]
  [29 61 58]
  [35 63 61]
  ...
  [ 2 28 26]
  [ 0 24 17]
  [ 0 23 16]]]


In [4]:
#video capturing

In [5]:
import cv2,time
video=cv2.VideoCapture(0)
a=1
while True:
    a=a+1
    check,frame=video.read()
    print(frame)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Capture",gray)
    key=cv2.waitKey(1)
    if key==ord('q'):
        break
        
print(a)
video.release()
cv2.destroyAllWindows()
    

[[[ 71  97  83]
  [ 72  98  84]
  [ 65 102  89]
  ...
  [ 60 133 113]
  [ 59 131 113]
  [ 59 131 113]]

 [[ 63  98  94]
  [ 65 100  97]
  [ 61 103  99]
  ...
  [ 58 134 120]
  [ 57 134 117]
  [ 55 131 115]]

 [[ 65 100  95]
  [ 66 102  96]
  [ 65 105  99]
  ...
  [ 62 139 120]
  [ 61 137 116]
  [ 60 136 115]]

 ...

 [[ 56  91  86]
  [ 54  90  84]
  [ 54  91  81]
  ...
  [  2  36  36]
  [  3  37  39]
  [  3  37  39]]

 [[ 57  89  86]
  [ 57  89  86]
  [ 58  89  80]
  ...
  [  1  35  36]
  [  3  34  38]
  [  4  35  39]]

 [[ 58  88  83]
  [ 58  88  83]
  [ 60  89  80]
  ...
  [  2  36  37]
  [  2  35  39]
  [  2  35  39]]]
[[[ 75  99  85]
  [ 76 100  86]
  [ 69 102  89]
  ...
  [ 64 132 116]
  [ 66 130 120]
  [ 64 128 117]]

 [[ 70 100  88]
  [ 69  99  87]
  [ 69 101  91]
  ...
  [ 58 131 110]
  [ 59 128 113]
  [ 61 131 115]]

 [[ 79 100  85]
  [ 77  99  84]
  [ 81 102  89]
  ...
  [ 72 142 115]
  [ 72 138 118]
  [ 66 132 113]]

 ...

 [[ 48  91  83]
  [ 47  90  81]
  [ 48  93  87]
  ..

In [6]:
#Face detection through saved image

In [7]:
face_cascade=cv2.CascadeClassifier(r"C:\Users\Sony\Desktop\haarcascade_frontalface_default.xml")

In [8]:
img=cv2.imread("C:\\Users\\Sony\\Desktop\\modi.jpg")

In [9]:
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [10]:
faces=face_cascade.detectMultiScale(gray,1.1,4)

In [11]:
for(x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),3)
    

In [12]:
cv2.imshow('img',img)
cv2.waitKey()

-1

In [13]:
import cv2

In [14]:
video_capture=cv2.VideoCapture(0)
while True:
    _, img = video_capture.read()
    cv2.imshow("face detection",img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()